### ISSUE TITLE
This crate does not build

### ISSUE THREAD

**Issue by 0nkery** [iron/logger#84] opened 2016-07-18 04:54 UTC
Maybe related to #80 .

``` shell
src/consumer/http.rs:20:11: 20:22 error: the trait bound `for<'r, 'r, 'r> logger::Logger: std::ops::Fn<(&'r mut iron::Request<'r, 'r>,)>` is not satisfied [E0277]
src/consumer/http.rs:20     chain.link_before(logger_before);
                                  ^~~~~~~~~~~
src/consumer/http.rs:20:11: 20:22 help: run `rustc --explain E0277` to see a detailed explanation
src/consumer/http.rs:20:11: 20:22 note: required because of the requirements on the impl of `iron::BeforeMiddleware` for `logger::Logger`
src/consumer/http.rs:20:11: 20:22 error: the trait bound `for<'r, 'r, 'r> logger::Logger: std::ops::FnOnce<(&'r mut iron::Request<'r, 'r>,)>` is not satisfied [E0277]
src/consumer/http.rs:20     chain.link_before(logger_before);
                                  ^~~~~~~~~~~
src/consumer/http.rs:20:11: 20:22 help: run `rustc --explain E0277` to see a detailed explanation
src/consumer/http.rs:20:11: 20:22 note: required because of the requirements on the impl of `iron::BeforeMiddleware` for `logger::Logger`
src/consumer/http.rs:21:11: 21:21 error: the trait bound `for<'r, 'r, 'r> logger::Logger: std::ops::Fn<(&'r mut iron::Request<'r, 'r>, iron::Response)>` is not satisfied [E0277]
src/consumer/http.rs:21     chain.link_after(logger_after);
                                  ^~~~~~~~~~
src/consumer/http.rs:21:11: 21:21 help: run `rustc --explain E0277` to see a detailed explanation
src/consumer/http.rs:21:11: 21:21 note: required because of the requirements on the impl of `iron::AfterMiddleware` for `logger::Logger`
src/consumer/http.rs:21:11: 21:21 error: the trait bound `for<'r, 'r, 'r> logger::Logger: std::ops::FnOnce<(&'r mut iron::Request<'r, 'r>, iron::Response)>` is not satisfied [E0277]
src/consumer/http.rs:21     chain.link_after(logger_after);
                                  ^~~~~~~~~~
src/consumer/http.rs:21:11: 21:21 help: run `rustc --explain E0277` to see a detailed explanation
src/consumer/http.rs:21:11: 21:21 note: required because of the requirements on the impl of `iron::AfterMiddleware` for `logger::Logger`
```

Built with Rust Nightly 1.12, Iron 0.3.

**Comment by untitaker** [comment] 2016-08-14 19:06
Duplicate of #80

**Closed by untitaker** 2016-08-14 19:06 UTC
